// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to suggest improvements to English sentences.
 *
 * - improveSentence - A function that handles the sentence improvement process.
 * - ImproveSentenceInput - The input type for the improveSentence function.
 * - ImproveSentenceOutput - The return type for the improveSentence function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveSentenceInputSchema = z.object({
  sentence: z.string().describe('The English sentence to improve.'),
});
export type ImproveSentenceInput = z.infer<typeof ImproveSentenceInputSchema>;

const ImproveSentenceOutputSchema = z.object({
  improvedSentence: z.string().describe('The improved English sentence.'),
  explanation: z
    .string()
    .describe('An explanation of the improvements made to the sentence.'),
});
export type ImproveSentenceOutput = z.infer<typeof ImproveSentenceOutputSchema>;

export async function improveSentence(input: ImproveSentenceInput): Promise<ImproveSentenceOutput> {
  return improveSentenceFlow(input);
}

const improveSentencePrompt = ai.definePrompt({
  name: 'improveSentencePrompt',
  input: {schema: ImproveSentenceInputSchema},
  output: {schema: ImproveSentenceOutputSchema},
  prompt: `You are an AI assistant that helps improve English sentences.

  Identify grammatical errors and suggest better word choices for the given sentence.
  Provide an improved sentence and explain the improvements made.

  Sentence: {{{sentence}}}
  `,
});

const improveSentenceFlow = ai.defineFlow(
  {
    name: 'improveSentenceFlow',
    inputSchema: ImproveSentenceInputSchema,
    outputSchema: ImproveSentenceOutputSchema,
  },
  async input => {
    const {output} = await improveSentencePrompt(input);
    return output!;
  }
);
